### ISSUE TITLE
Vulnerabilities and maintenance

### ISSUE THREAD

**Issue by thegeorgeous** [ejschmitt/delayed_job_web#133]
@andyatkinson @ejschmitt 

The gem currently has multiple vulnerabilities in its dependencies and doesn't seem to be maintained. I use this gem for work regularly and would be happy to help maintain the gem if you are still looking for maintainers. Alternatively, I could open PRs to fix these issues.

**Comment by ejschmitt** [comment]
Thanks for reaching out, you are right! I sent an invite.
