### ISSUE TITLE
Integrate delayed_job_interface inside activeadmin

### ISSUE THREAD

**Issue by devilankur18** [ejschmitt/delayed_job_web#27]
Please help me out to integrate the delayed_job_web inside activeadmin dashboard

**Comment by AaronGaim** [comment]
A version without Device based on @hammady answer to allow only admin users to enter delayed jobs

	# config/routes.rb (secure /djmon route to only authenticated admin_user):
	constraints ManagerRouteConstraint.new do
		match "/djmon" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
		#get 'dashboard', to: 'manager_dashboards#show'
	end
	# app/admin/djmon.rb (register custom page to embed the whole thing in iframe)
	ActiveAdmin.register_page "Delayed Job Monitoring" do
	  content do
	    iframe style: "width: 100%; height: 100vh;", src: '/djmon/overview' do
	    end
	  end
	end
	# app/constraint/manager_route_constraint.rb (register custom page to embed the whole thing in iframe)
	class ManagerRouteConstraint
	  def matches? request
	    user = current_user(request)
	    user.present? && user.admin?
	  end
	
	  def current_user request
	    User.find_by_id(request.session[:user_id])
	  end
	end
