### ISSUE TITLE
Integration with Rails 5

### ISSUE THREAD

**Issue by janraasch** [ejschmitt/delayed_job_web#84]
Hi there, Happy New Year!

Currently, when trying to install this together with `rails v5.0.0.beta1`, `bundler` will install 

```
  * sinatra-1.0.gem
  * delayed_job_web-1.2.5.gem
```

since `1.0` is the only version of `sinatra` which does not restrict itself to `rack v1.x, "< 2"`, and `rails v5.0.0.beta1` runs on `rack 2.0.0.alpha`.

Are you planning to support Rails 5? If so, how could we move forward to achieve that goal?

**Comment by chrismear** [comment]
Probably the best approach is to help get a new release of Sinatra 1 released that is compatible with Rack 2: https://github.com/sinatra/sinatra/pull/1061

**Comment by janraasch** [comment]
@chrismear, sounds good. I suppose this is issue is *onhold* until sinatra/sinatra#1061 is decided then.

**Comment by devilankur18** [comment]
+1

**Comment by devilankur18** [comment]
This fixed the issue 

```
gem "sinatra", github: 'sinatra/sinatra'
gem "rack-protection", github: 'sinatra/rack-protection'
gem "delayed_job_web"
```

**Comment by wfried** [comment]
There is now a release of sinatra (v2.0.0.beta2) which supports Rails 5.

**Comment by tom-lord** [comment]
I also just encountered this issue when upgrading an application to Rails 5.

Loading the application fails with the following error:

    gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require':
      cannot load such file -- rack/showexceptions (LoadError)

The current solution is to simply add the line:

    gem 'sinatra', '>= 2.0.0.beta2'

to your `Gemfile`.

For more detail, see [this](https://github.com/sinatra/sinatra/issues/1055) issue in Sinatra.

**Comment by mmhan** [comment]
Wondering what's the updated solution for this. Is there a new version lined up for this gem?

**Comment by janraasch** [comment]
Since all sinatra issues are solved (see links to issues above), the problem is fixed. We already use this gem with `rails v5` in production.

**Comment by ACPK** [comment]
@ejschmitt - Should the readme be updated to say it supports Rails5?

**Comment by andyatkinson** [comment]
@ACPK Sure. Could you please do that as a new PR and I will merge it in? According to @janraasch they're using it with Rails 5.
